SELECT s.sid
,      s.username
,      s.event
,      s.p1
,      s.p2
,      s.p3
,      s.wait_time
,      s.seconds_in_wait
,      s.state 
FROM gv$session s 
WHERE s.event != 'AQ Proxy Cleanup Wait'
  AND s.event != 'ASM background timer'
  AND s.event != 'DBRM Logical Idle Wait'
  AND s.event != 'DIAG idle wait'
  AND s.event != 'EMON idle wait'
  AND s.event != 'EMON slave idle wait'
  AND s.event != 'IORM Scheduler Slave Idle Wait'
  AND s.event != 'KSV master wait'
  AND s.event != 'LNS ASYNC archive log'
  AND s.event != 'LNS ASYNC dest activation'
  AND s.event != 'LNS ASYNC end of log'
  AND s.event != 'LogMiner: client waiting for transaction'
  AND s.event != 'LogMiner: generic process sleep'
  AND s.event != 'LogMiner: reader waiting for more redo'
  AND s.event != 'LogMiner: slave waiting for activate message'
  AND s.event != 'LogMiner: waiting for processes to soft detach'
  AND s.event != 'LogMiner: wakeup event for builder'
  AND s.event != 'LogMiner: wakeup event for preparer'
  AND s.event != 'LogMiner: wakeup event for reader'
  AND s.event != 'MRP redo arrival'
  AND s.event != 'Null event'
  AND s.event != 'PING'
  AND s.event != 'PX Deq Credit: need buffer'
  AND s.event != 'PX Deq Credit: send blkd'
  AND s.event != 'PX Deq: Execute Reply'
  AND s.event != 'PX Deq: Execution Msg'
  AND s.event != 'PX Deq: Par Recov Execute'
  AND s.event != 'PX Deq: Signal ACK'
  AND s.event != 'PX Deq: Table Q Normal'
  AND s.event != 'PX Deq: Table Q Sample'
  AND s.event != 'PX Deque wait'
  AND s.event != 'PX Idle Wait'
  AND s.event != 'Queue Monitor Shutdown Wait'
  AND s.event != 'Queue Monitor Slave Wait'
  AND s.event != 'Queue Monitor Wait'
  AND s.event != 'SQL*Net message from client'
  AND s.event != 'SQL*Net message to client'
  AND s.event != 'SQL*Net more data from client'
  AND s.event != 'STREAMS apply coord waiting for slave message'
  AND s.event != 'STREAMS apply slave idle wait'
  AND s.event != 'STREAMS apply slave waiting for coord message'
  AND s.event != 'STREAMS capture process filter callback wait for ruleset'
  AND s.event != 'STREAMS fetch slave waiting for txns'
  AND s.event != 'STREAMS waiting for subscribers to catch up'
  AND s.event != 'Space Manager: slave idle wait'
  AND s.event != 'Streams AQ: RAC qmn coordinator idle wait'
  AND s.event != 'Streams AQ: deallocate messages from Streams Pool'
  AND s.event != 'Streams AQ: delete acknowledged messages'
  AND s.event != 'Streams AQ: qmn coordinator idle wait'
  AND s.event != 'Streams AQ: qmn slave idle wait'
  AND s.event != 'Streams AQ: waiting for messages in the queue'
  AND s.event != 'Streams AQ: waiting for time management or cleanup tasks'
  AND s.event != 'Streams capture: waiting for archive log'
  AND s.event != 'Streams fetch slave: waiting for txns'
  AND s.event != 'class slave wait'
  AND s.event != 'client message'
  AND s.event != 'cmon timer'
  AND s.event != 'dispatcher timer'
  AND s.event != 'fbar timer'
  AND s.event != 'gcs for action'
  AND s.event != 'gcs remote message'
  AND s.event != 'ges remote message'
  AND s.event != 'i/o slave wait'
  AND s.event != 'jobq slave wait'
  AND s.event != 'knlqdeq'
  AND s.event != 'lock manager wait for remote message'
  AND s.event != 'master wait'
  AND s.event != 'null event'
  AND s.event != 'parallel query dequeue'
  AND s.event != 'parallel recovery coordinator waits for slave cleanup'
  AND s.event != 'parallel recovery slave idle wait'
  AND s.event != 'parallel recovery slave next change'
  AND s.event != 'parallel recovery slave wait for change'
  AND s.event != 'pipe get'
  AND s.event != 'pmon timer'
  AND s.event != 'pool server timer'
  AND s.event != 'queue messages'
  AND s.event != 'rdbms ipc message'
  AND s.event != 'slave wait'
  AND s.event != 'smon timer'
  AND s.event != 'virtual circuit status'
  AND s.event != 'wait for activate message'
  AND s.event != 'wait for unread message on broadcast channel'
  AND s.event != 'wakeup event for builder'
  AND s.event != 'wakeup event for preparer'
  AND s.event != 'wakeup event for reader'
  AND s.event != 'wakeup time manager'
  AND s.event != 'watchdog main loop'
  ORDER BY s.seconds_in_wait desc